// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildTool } from "./BuildTool";
import type { LatexEngine } from "./LatexEngine";
import type { TeXProvider } from "./TeXProvider";

export type AppConfigV1 = { schemaVersion: number, recentProjects: Array<string>, openLastProject: boolean, autosave: boolean, automaticBuilds: boolean, automaticBuildDelaySeconds: number, editorFontSize: number, tabWidth: number, showLineNumbers: boolean, wordWrap: boolean, autoCloseBrackets: boolean, latexEngine: LatexEngine, buildTool: BuildTool, texProvider: TeXProvider | null, managedRuntimeRecordPath: string | null, showProblemsOnFailure: boolean, };
