// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

export type BuildDiagnostic = { severity: DiagnosticSeverity, relativePath: string | null, line: number | null, message: string, };
