// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildDiagnostic } from "./BuildDiagnostic";

export type BuildDiagnosticGroup = { primary: BuildDiagnostic, related: Array<BuildDiagnostic>, };
