// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildTool } from "./BuildTool";
import type { LatexEngine } from "./LatexEngine";
import type { ProjectId } from "./ProjectId";

export type BuildRequest = { projectId: ProjectId, entryFile: string, engine: LatexEngine, tool: BuildTool, executablePath: string, searchDirectories: Array<string>, };
