// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildDiagnosticGroup } from "./BuildDiagnosticGroup";

export type BuildResult = { succeeded: boolean, log: string, previewPdfPath: string | null, projectPdfPath: string | null, diagnostics: Array<BuildDiagnosticGroup>, missingPackageFile: string | null, };
