// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildResult } from "./BuildResult";

export type BuildEvent = { "stage": "started" } | { "stage": "output", chunk: string, } | { "stage": "finished", result: BuildResult, } | { "stage": "cancelled" };
