// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundledTemplateCategory } from "./BundledTemplateCategory";
import type { LatexEngine } from "./LatexEngine";
import type { TemplateCodeLanguage } from "./TemplateCodeLanguage";
import type { TemplateCodeStyle } from "./TemplateCodeStyle";
import type { TemplateSectionNumbering } from "./TemplateSectionNumbering";

export type BundledTemplateManifestV2 = { schemaVersion: number, id: string, name: string, description: string, category: BundledTemplateCategory, sortOrder: number, engine: LatexEngine, entry: string, preview: string, previewVariants: { [key in string]?: string }, codeStyles: Array<TemplateCodeStyle>, codeLanguages: Array<TemplateCodeLanguage>, defaultCodeStyle: TemplateCodeStyle | null, defaultCodeLanguages: Array<TemplateCodeLanguage>, sectionNumberings: Array<TemplateSectionNumbering>, defaultSectionNumbering: TemplateSectionNumbering | null, };
