// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionKind } from "./CompletionKind";

export type CompletionItem = { label: string, insertText: string, detail: string, kind: CompletionKind, };
