// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedRuntimeRecordV2 } from "./ManagedRuntimeRecordV2";

export type InstalledRuntime = { record: ManagedRuntimeRecordV2, installedSize: number, active: boolean, };
