// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeArchitecture } from "./RuntimeArchitecture";
import type { RuntimePlatform } from "./RuntimePlatform";
import type { RuntimeVariant } from "./RuntimeVariant";

export type ManagedRuntimeRecordV2 = { schemaVersion: number, runtimeVersion: string, texLiveYear: number, variant: RuntimeVariant, platform: RuntimePlatform, architecture: RuntimeArchitecture, rootPath: string, tools: { [key in string]?: string }, };
