// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectEntry = { name: string, relativePath: string, isDirectory: boolean, children: Array<ProjectEntry>, };
