// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectVersionId } from "./ProjectVersionId";
import type { ProjectVersionKind } from "./ProjectVersionKind";
import type { VersionFileEntry } from "./VersionFileEntry";
import type { VersionPreviewStatus } from "./VersionPreviewStatus";

export type ProjectVersionManifest = { schemaVersion: number, id: ProjectVersionId, projectRecordId: string, name: string, createdAt: string, kind: ProjectVersionKind, mainDocument: string | null, directories: Array<string>, files: Array<VersionFileEntry>, totalSize: number, previewStatus: VersionPreviewStatus, previewError: string | null, previewPdfPath: string | null, };
