// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectVersionId } from "./ProjectVersionId";
import type { ProjectVersionKind } from "./ProjectVersionKind";
import type { VersionPreviewStatus } from "./VersionPreviewStatus";

export type ProjectVersionSummary = { id: ProjectVersionId, name: string, createdAt: string, kind: ProjectVersionKind, mainDocument: string | null, fileCount: number, totalSize: number, previewStatus: VersionPreviewStatus, previewError: string | null, };
