// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSessionV2 = { schemaVersion: number, projectPath: string, mainDocument: string | null, openDocuments: Array<string>, selectedDocument: string | null, outlineExpanded: boolean, outlineHeight: number, };
