// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectCompletionIndex = { labels: Array<string>, citations: Array<string>, packages: Array<string>, classes: Array<string>, inputPaths: Array<string>, imagePaths: Array<string>, };
