// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedRuntimeRecordV2 } from "./ManagedRuntimeRecordV2";

export type RuntimeInstallEvent = { "stage": "checking" } | { "stage": "downloading", received: number, total: number, bytesPerSecond: number, } | { "stage": "verifying" } | { "stage": "installing" } | { "stage": "ready", record: ManagedRuntimeRecordV2, } | { "stage": "failed", message: string, } | { "stage": "cancelled" };
