// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeArchitecture } from "./RuntimeArchitecture";
import type { RuntimePlatform } from "./RuntimePlatform";

export type RuntimeEnvironment = { platform: RuntimePlatform, architecture: RuntimeArchitecture, };
