// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeArchitecture } from "./RuntimeArchitecture";
import type { RuntimeArchivePart } from "./RuntimeArchivePart";
import type { RuntimePlatform } from "./RuntimePlatform";
import type { RuntimeVariant } from "./RuntimeVariant";

export type RuntimeAsset = { variant: RuntimeVariant, platform: RuntimePlatform, architecture: RuntimeArchitecture, downloadUrl: string | null, downloadParts: Array<RuntimeArchivePart> | null, compressedSize: number, installedSize: number, sha256: string, tools: { [key in string]?: string }, };
