// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeAsset } from "./RuntimeAsset";

export type RuntimeManifestV2 = { schemaVersion: number, runtimeVersion: string, texLiveYear: number, assets: Array<RuntimeAsset>, };
