// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentRevision } from "./DocumentRevision";

export type SaveOutcome = { "status": "saved", revision: DocumentRevision, } | { "status": "conflict", diskRevision: DocumentRevision | null, } | { "status": "missing" };
