// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncTeXPdfTarget = { page: number, x: number | null, yFromTop: number | null, };
