// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TemplateReview = { sourcePath: string, includedFiles: Array<string>, excludedFiles: Array<string>, totalSize: number, };
