// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateCodeLanguage } from "./TemplateCodeLanguage";
import type { TemplateCodeStyle } from "./TemplateCodeStyle";

export type TemplateInstantiationOptions = { codeStyle: TemplateCodeStyle | null, codeLanguages: Array<TemplateCodeLanguage> | null, };
