// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateCodeLanguage } from "./TemplateCodeLanguage";
import type { TemplateCodeStyle } from "./TemplateCodeStyle";
import type { TemplateProjectStructure } from "./TemplateProjectStructure";
import type { TemplateSectionNumbering } from "./TemplateSectionNumbering";
import type { TemplateTitlePage } from "./TemplateTitlePage";

export type TemplateInstantiationOptions = { codeStyle: TemplateCodeStyle | null, codeLanguages: Array<TemplateCodeLanguage> | null, sectionNumbering: TemplateSectionNumbering | null, titlePage: TemplateTitlePage | null, projectStructure: TemplateProjectStructure | null, };
