// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolExecutable } from "./ToolExecutable";

export type ToolchainStatus = { engines: { [key in string]?: ToolExecutable }, latexmk: ToolExecutable | null, synctex: ToolExecutable | null, tlmgr: ToolExecutable | null, };
