// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionFileKind } from "./VersionFileKind";

export type VersionFileEntry = { relativePath: string, kind: VersionFileKind, blobSha256: string | null, size: number, unixMode: number | null, linkTarget: string | null, };
