// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectVersionSummary } from "./ProjectVersionSummary";

export type VersionRestoreOutcome = { recoveryVersion: ProjectVersionSummary, changedPaths: Array<string>, mainDocument: string | null, };
