// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionDiffLineKind } from "./VersionDiffLineKind";

export type VersionDiffLine = { kind: VersionDiffLineKind, text: string, oldLine: number | null, newLine: number | null,
/**
 * One-based line in the saved document before which a deletion is rendered.
 * `new_line_count + 1` places it after the final line.
 */
anchorNewLine: number, };
