// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectVersionId } from "./ProjectVersionId";
import type { VersionPreviewStatus } from "./VersionPreviewStatus";

export type VersionPreviewEvent = { versionId: ProjectVersionId, status: VersionPreviewStatus, message: string | null, };
