// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionDiffLine } from "./VersionDiffLine";

export type VersionFileDiff = { relativePath: string, additions: number, deletions: number, binary: boolean, lines: Array<VersionDiffLine>, };
