import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import type {
  AppConfigV1,
  AppUpdateInfo,
  BuildRequest,
  BuildResult,
  BundledTemplateManifestV2,
  DocumentRevision,
  DocumentSnapshot,
  ManagedRuntimeRecordV2,
  InstalledRuntime,
  OutlineItem,
  ProjectCompletionIndex,
  ProjectEntry,
  ProjectHandle,
  ProjectId,
  ProjectSessionV2,
  ProjectVersionId,
  ProjectVersionSummary,
  ReplacePreview,
  RuntimeInstallEvent,
  RuntimeEnvironment,
  RuntimeManifestV2,
  RuntimeVariant,
  SaveOutcome,
  SearchQuery,
  SearchResult,
  SyncTeXPdfTarget,
  SyncTeXSourceTarget,
  ToolchainStatus,
  StorageUsage,
  TemplateReview,
  TemplateCodeStyle,
  TemplateSectionNumbering,
  TemplateTitlePage,
  TemplateInstantiationOptions,
  PersonalTemplateManifestV2,
  VersionChangeSummary,
  VersionFileDiff,
  VersionLineSummary,
  VersionPreviewEvent,
  VersionRestoreOutcome,
  VersionSnapshotReview,
} from "./types";

export const isDesktop = () => "__TAURI_INTERNALS__" in window;

export const api = {
  loadConfig: () => invoke<AppConfigV1>("load_config"),
  saveConfig: (config: AppConfigV1) => invoke<void>("save_config", { config }),
  loadSession: (projectPath: string) => invoke<ProjectSessionV2 | null>("load_session", { projectPath }),
  saveSession: (session: ProjectSessionV2) => invoke<void>("save_session", { session }),
  openProject: (path: string) => invoke<ProjectHandle>("open_project", { path }),
  closeProject: (projectId: ProjectId) => invoke<void>("close_project", { projectId }),
  createProject: (parentPath: string, name: string) => invoke<string>("create_project", { parentPath, name }),
  createProjectFromTemplate: (parentPath: string, name: string, template: string, options: TemplateInstantiationOptions | null = null) => invoke<string>("create_project_from_template", { parentPath, name, template, options }),
  listBundledTemplates: () => invoke<BundledTemplateManifestV2[]>("list_bundled_templates"),
  bundledTemplatePreview: (
    template: string,
    style: TemplateCodeStyle | null = null,
    sectionNumbering: TemplateSectionNumbering | null = null,
    titlePage: TemplateTitlePage | null = null,
  ) => invoke<string>("bundled_template_preview", { template, style, sectionNumbering, titlePage }),
  scanProject: (projectId: ProjectId) => invoke<ProjectEntry[]>("scan_project", { projectId }),
  openDocument: (projectId: ProjectId, relativePath: string) => invoke<DocumentSnapshot>("open_document", { projectId, relativePath }),
  documentRevision: (projectId: ProjectId, relativePath: string) => invoke<DocumentRevision | null>("document_revision", { projectId, relativePath }),
  locateDocument: (projectId: ProjectId, fileIdentifier: string) => invoke<string | null>("locate_document", { projectId, fileIdentifier }),
  saveDocument: (
    projectId: ProjectId,
    relativePath: string,
    text: string,
    baseRevision: DocumentRevision | null,
    overwriteConflict = false,
  ) => invoke<SaveOutcome>("save_document", { projectId, relativePath, text, baseRevision, overwriteConflict }),
  saveDocumentCopy: (path: string, text: string) => invoke<DocumentRevision>("save_document_copy", { path, text }),
  createFile: (projectId: ProjectId, parent: string, name: string) => invoke<string>("create_file", { projectId, parent, name }),
  createFolder: (projectId: ProjectId, parent: string, name: string) => invoke<string>("create_folder", { projectId, parent, name }),
  renameEntry: (projectId: ProjectId, relativePath: string, newName: string) => invoke<string>("rename_entry", { projectId, relativePath, newName }),
  duplicateEntry: (projectId: ProjectId, relativePath: string) => invoke<string>("duplicate_entry", { projectId, relativePath }),
  moveEntry: (projectId: ProjectId, relativePath: string, destinationFolder: string) => invoke<string>("move_entry", { projectId, relativePath, destinationFolder }),
  trashEntry: (projectId: ProjectId, relativePath: string) => invoke<void>("trash_entry", { projectId, relativePath }),
  uploadEntries: (projectId: ProjectId, destinationFolder: string, sources: string[]) => invoke<string[]>("upload_entries", { projectId, destinationFolder, sources }),
  templateReview: (sourcePath: string) => invoke<TemplateReview>("template_review", { sourcePath }),
  createPersonalTemplate: (name: string, review: TemplateReview, previewBase64: string | null = null) => invoke<PersonalTemplateManifestV2>("create_personal_template", { name, review, previewBase64 }),
  templatePreviewPdf: (review: TemplateReview) => invoke<string | null>("template_preview_pdf", { review }),
  listPersonalTemplates: () => invoke<PersonalTemplateManifestV2[]>("list_personal_templates"),
  createProjectFromPersonalTemplate: (id: string, parentPath: string, name: string) => invoke<string>("create_project_from_personal_template", { id, parentPath, name }),
  removePersonalTemplate: (id: string) => invoke<void>("remove_personal_template", { id }),
  personalTemplatePreview: (id: string) => invoke<string | null>("personal_template_preview", { id }),
  search: (projectId: ProjectId, query: SearchQuery, buffers: Array<{ relativePath: string; text: string }>) => invoke<SearchResult[]>("project_search", { projectId, query, buffers }),
  replacePreview: (projectId: ProjectId, query: SearchQuery, replacement: string, buffers: Array<{ relativePath: string; text: string }>) => invoke<ReplacePreview[]>("replace_preview", { projectId, query, replacement, buffers }),
  applyReplacements: (projectId: ProjectId, changes: ReplacePreview[], undo = false) => invoke<void>("apply_replacements", { projectId, changes, undo }),
  outline: (relativePath: string, text: string) => invoke<OutlineItem[]>("document_outline", { relativePath, text }),
  completionIndex: (projectId: ProjectId) => invoke<ProjectCompletionIndex>("completion_index", { projectId }),
  listProjectVersions: (projectId: ProjectId) => invoke<ProjectVersionSummary[]>("list_project_versions", { projectId }),
  reviewProjectVersion: (projectId: ProjectId, mainDocument: string | null) => invoke<VersionSnapshotReview>("review_project_version", { projectId, mainDocument }),
  createProjectVersion: (projectId: ProjectId, name: string, mainDocument: string | null) => invoke<ProjectVersionSummary>("create_project_version", { projectId, name, mainDocument }),
  renameProjectVersion: (projectId: ProjectId, versionId: ProjectVersionId, name: string) => invoke<ProjectVersionSummary>("rename_project_version", { projectId, versionId, name }),
  deleteProjectVersion: (projectId: ProjectId, versionId: ProjectVersionId) => invoke<void>("delete_project_version", { projectId, versionId }),
  projectVersionTree: (projectId: ProjectId, versionId: ProjectVersionId) => invoke<ProjectEntry[]>("project_version_tree", { projectId, versionId }),
  readProjectVersionFile: (projectId: ProjectId, versionId: ProjectVersionId, relativePath: string) => invoke<string>("read_project_version_file", { projectId, versionId, relativePath }),
  compareProjectVersion: (projectId: ProjectId, versionId: ProjectVersionId) => invoke<VersionChangeSummary>("compare_project_version", { projectId, versionId }),
  projectVersionLineSummary: (projectId: ProjectId, versionId: ProjectVersionId, buffers: Array<{ relativePath: string; text: string }>) => invoke<VersionLineSummary>("project_version_line_summary", { projectId, versionId, buffers }),
  projectVersionFileDiff: (projectId: ProjectId, versionId: ProjectVersionId, relativePath: string, currentText: string | null) => invoke<VersionFileDiff>("project_version_file_diff", { projectId, versionId, relativePath, currentText }),
  restoreProjectVersion: (projectId: ProjectId, versionId: ProjectVersionId, currentMainDocument: string | null) => invoke<VersionRestoreOutcome>("restore_project_version", { projectId, versionId, currentMainDocument }),
  buildProjectVersionPreview: (request: BuildRequest, versionId: ProjectVersionId) => invoke<ProjectVersionSummary>("build_project_version_preview", { request, versionId }),
  readProjectVersionPreview: (projectId: ProjectId, versionId: ProjectVersionId) => invoke<string | null>("read_project_version_preview", { projectId, versionId }),
  detectSystemTex: () => invoke<ToolchainStatus>("detect_system_tex"),
  build: (request: BuildRequest) => invoke<BuildResult>("build_project", { request }),
  cancelBuild: () => invoke<void>("cancel_build"),
  readPreviewPdf: (projectId: ProjectId, path: string) => invoke<string>("read_preview_pdf", { projectId, path }),
  synctexForward: (projectId: ProjectId, executablePath: string, sourceRelative: string, line: number, column: number, pdfPath: string) => invoke<SyncTeXPdfTarget | null>("synctex_forward", { projectId, executablePath, sourceRelative, line, column, pdfPath }),
  synctexInverse: (projectId: ProjectId, executablePath: string, pdfPath: string, page: number, x: number, yFromTop: number) => invoke<SyncTeXSourceTarget | null>("synctex_inverse", { projectId, executablePath, pdfPath, page, x, yFromTop }),
  synctexProjectVersionForward: (projectId: ProjectId, versionId: ProjectVersionId, executablePath: string, sourceRelative: string, line: number, column: number) => invoke<SyncTeXPdfTarget | null>("synctex_project_version_forward", { projectId, versionId, executablePath, sourceRelative, line, column }),
  synctexProjectVersionInverse: (projectId: ProjectId, versionId: ProjectVersionId, executablePath: string, page: number, x: number, yFromTop: number) => invoke<SyncTeXSourceTarget | null>("synctex_project_version_inverse", { projectId, versionId, executablePath, page, x, yFromTop }),
  runtimeManifest: () => invoke<RuntimeManifestV2>("runtime_manifest"),
  installedRuntimes: () => invoke<ManagedRuntimeRecordV2[]>("installed_runtimes"),
  runtimeEnvironment: () => invoke<RuntimeEnvironment>("runtime_environment"),
  runtimeInventory: (activeRecordPath: string | null) => invoke<InstalledRuntime[]>("runtime_inventory", { activeRecordPath }),
  removeRuntime: (record: ManagedRuntimeRecordV2, activeRecordPath: string | null) => invoke<void>("remove_runtime", { record, activeRecordPath }),
  storageUsage: () => invoke<StorageUsage>("storage_usage"),
  clearStorage: (downloads: boolean, staging: boolean, buildCache: boolean) => invoke<StorageUsage>("clear_storage", { downloads, staging, buildCache }),
  runtimeToolchain: (record: ManagedRuntimeRecordV2) => invoke<ToolchainStatus>("runtime_toolchain", { record }),
  installRuntime: (manifest: RuntimeManifestV2, variant: RuntimeVariant) => invoke<ManagedRuntimeRecordV2>("install_runtime", { manifest, variant }),
  cancelRuntimeInstall: () => invoke<void>("cancel_runtime_install"),
  installMissingPackage: (record: ManagedRuntimeRecordV2, missingFile: string) => invoke<string>("install_missing_package", { record, missingFile }),
  checkForUpdates: () => invoke<AppUpdateInfo>("check_for_updates"),
};

export const events = {
  projectChanged: (handler: (paths: string[]) => void): Promise<UnlistenFn> =>
    listen<{ paths: string[] }>("project://changed", (event) => handler(event.payload.paths)),
  runtimeInstall: (handler: (event: RuntimeInstallEvent) => void): Promise<UnlistenFn> =>
    listen<RuntimeInstallEvent>("runtime://install", (event) => handler(event.payload)),
  menuAction: (handler: (action: string) => void): Promise<UnlistenFn> =>
    listen<string>("menu://action", (event) => handler(event.payload)),
  versionPreview: (handler: (event: VersionPreviewEvent) => void): Promise<UnlistenFn> =>
    listen<VersionPreviewEvent>("version://preview", (event) => handler(event.payload)),
};
